# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('url_image', models.URLField(blank=True, null=True)),
                ('author_choice', models.BooleanField(default=False)),
            ],
        ),
    ]
