# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile10mins', '0002_auto_20171104_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='belong_to',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
