# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile10mins', '0003_auto_20171104_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='owner',
        ),
    ]
